### ISSUE TITLE
layout specified in config file

### ISSUE THREAD

**Issue by andy5995** [luiemilio/jekyll_post_generator#1]
```
layout: post
```

Some projects may not use "post" for the layout, so that would be a good option for the config.

[This project](https://github.com/up-for-grabs/up-for-grabs.net) doesn't use it at all (here's an example of one of their project files)

```
name: yes
desc: Implementation of yes UNIX command in various languages
site: https://github.com/mubaris/yes
tags:
# Note those are tags categorizing your project, not issue labels.
- linux
- commands
- noobs
- simple
upforgrabs:
  name: up-for-grabs
  link: https://github.com/mubaris/yes/labels/up-for-grabs
```

Up to you of course, if you want to add features that make it more flexible. This is going to work great for our project at mhwKB! Thanks again!

**Comment by luiemilio** [comment]
fields are more flexible now
